channels:
- conda-forge
- nodefaults
dependencies:
- invoke=2.2.0
- packaging
- pyyaml
# applications
- jupyterlab=4.1.8
# - jupyter-collaboration=2.1.1
- nbconvert=7.16.4
- notebook=7.1.3
# extensions
# - jupyter-offlinenotebook=0.3.1
# - jupyterlab-fasta=3.3
# C++ Kernel
- xeus-cling=0.13.0
# - xtensor=0.23.10
# - xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
